server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.11.72:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal_portal_masukmotor_service
    journal:
      labels:
        job: masukmotor-portal-service
        host: __HOSTNAME__
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        regex: 'portal.service'
        action: keep
      - source_labels: ['__hostname__']
        target_label: 'instance'